# Generated by Django 5.2.15 on 2026-06-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivityevent',
            new_name='analytics_u_user_id_21d7c6_idx',
            old_name='analytics_u_user_id_6e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivityevent',
            new_name='analytics_u_event_t_fe933d_idx',
            old_name='analytics_u_event_t_8c8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivityevent',
            new_name='analytics_u_session_021554_idx',
            old_name='analytics_u_session_4b2c1d_idx',
        ),
    ]
