# Generated by Django 5.2.15 on 2026-06-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_clubevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('africa', 'Africa'), ('news', 'News'), ('strategy', 'Strategy'), ('blog', 'Blog')], default='general', max_length=20),
        ),
    ]
