# Generated by Django 5.2.15 on 2026-06-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_forumpost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('fide_title', models.CharField(blank=True, max_length=10)),
                ('hourly_rate_eur', models.PositiveIntegerField(default=25)),
                ('languages', models.CharField(default='fr,en', max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=40)),
                ('is_available', models.BooleanField(default=True)),
                ('booking_url', models.URLField(blank=True, help_text='Calendly ou lien externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_username', models.CharField(blank=True, max_length=80)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=80)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streamer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
