# Generated by Django 5.2.15 on 2026-06-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_db_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_f2ad08_idx',
            old_name='notificatio_user_id_7e8f9a_idx',
        ),
    ]
