# Generated by Django 5.2.15 on 2026-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("bullet", "Bullet"),
                            ("blitz", "Blitz"),
                            ("rapid", "Rapid"),
                            ("classical", "Classical"),
                            ("puzzle", "Puzzle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("elo", models.PositiveIntegerField(default=1200)),
                ("peak_elo", models.PositiveIntegerField(default=1200)),
                ("games_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RatingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=20)),
                ("elo_before", models.PositiveIntegerField()),
                ("elo_after", models.PositiveIntegerField()),
                ("change", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
