# Generated by Django 5.2.15 on 2026-06-04 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0002_initial"),
        ("ratings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playerrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ratinghistory",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="ratinghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="playerrating",
            index=models.Index(
                fields=["mode", "-elo"], name="ratings_pla_mode_072042_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playerrating",
            unique_together={("user", "mode")},
        ),
    ]
