# Generated by Django 5.2.15 on 2026-06-04 11:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("DZ", "Algeria"),
                            ("AO", "Angola"),
                            ("BJ", "Benin"),
                            ("BW", "Botswana"),
                            ("BF", "Burkina Faso"),
                            ("BI", "Burundi"),
                            ("CM", "Cameroon"),
                            ("CV", "Cape Verde"),
                            ("CF", "Central African Republic"),
                            ("TD", "Chad"),
                            ("KM", "Comoros"),
                            ("CG", "Congo"),
                            ("CD", "DR Congo"),
                            ("CI", "Côte d'Ivoire"),
                            ("DJ", "Djibouti"),
                            ("EG", "Egypt"),
                            ("GQ", "Equatorial Guinea"),
                            ("ER", "Eritrea"),
                            ("SZ", "Eswatini"),
                            ("ET", "Ethiopia"),
                            ("GA", "Gabon"),
                            ("GM", "Gambia"),
                            ("GH", "Ghana"),
                            ("GN", "Guinea"),
                            ("GW", "Guinea-Bissau"),
                            ("KE", "Kenya"),
                            ("LS", "Lesotho"),
                            ("LR", "Liberia"),
                            ("LY", "Libya"),
                            ("MG", "Madagascar"),
                            ("MW", "Malawi"),
                            ("ML", "Mali"),
                            ("MR", "Mauritania"),
                            ("MU", "Mauritius"),
                            ("MA", "Morocco"),
                            ("MZ", "Mozambique"),
                            ("NA", "Namibia"),
                            ("NE", "Niger"),
                            ("NG", "Nigeria"),
                            ("RW", "Rwanda"),
                            ("ST", "São Tomé and Príncipe"),
                            ("SN", "Senegal"),
                            ("SC", "Seychelles"),
                            ("SL", "Sierra Leone"),
                            ("SO", "Somalia"),
                            ("ZA", "South Africa"),
                            ("SS", "South Sudan"),
                            ("SD", "Sudan"),
                            ("TZ", "Tanzania"),
                            ("TG", "Togo"),
                            ("TN", "Tunisia"),
                            ("UG", "Uganda"),
                            ("ZM", "Zambia"),
                            ("ZW", "Zimbabwe"),
                            ("XX", "Other"),
                        ],
                        default="XX",
                        max_length=2,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("ar", "Arabic"),
                            ("pt", "Portuguese"),
                            ("sw", "Swahili"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "is_african_highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Featured African chess player on homepage",
                    ),
                ),
                ("low_bandwidth_mode", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=20)),
                ("fide_id", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("games_won", models.PositiveIntegerField(default=0)),
                ("games_drawn", models.PositiveIntegerField(default=0)),
                ("games_lost", models.PositiveIntegerField(default=0)),
                ("puzzles_solved", models.PositiveIntegerField(default=0)),
                ("best_win_streak", models.PositiveIntegerField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("total_play_time_seconds", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
