# Generated by Django 5.2.15 on 2026-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userstats_daily_puzzle_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='free', max_length=20),
        ),
    ]
