# Generated by Django 5.2.15 on 2026-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_premium_until_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='puzzle_rush_daily_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='puzzle_rush_last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
