apiVersion: 1

policies:
  - orgId: 1
    receiver: africhess-oncall
    group_by: ["alertname", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: africhess-oncall
        matchers:
          - label=severity
            match: "="
            value: critical
        continue: true
      - receiver: africhess-email
        matchers:
          - label=severity
            match: "="
            value: critical
        continue: false
      - receiver: africhess-oncall
        matchers:
          - label=severity
            match: "="
            value: warning
