"""ISO 3166-1 alpha-2 countries for registration and analytics."""

WORLD_COUNTRIES = [
    ("AF", "Afghanistan", "Afghanistan", False),
    ("ZA", "South Africa", "Afrique du Sud", True),
    ("AL", "Albania", "Albanie", False),
    ("DZ", "Algeria", "Algérie", True),
    ("DE", "Germany", "Allemagne", False),
    ("AD", "Andorra", "Andorre", False),
    ("AO", "Angola", "Angola", True),
    ("AI", "Anguilla", "Anguilla", False),
    ("AQ", "Antarctica", "Antarctique", False),
    ("AG", "Antigua and Barbuda", "Antigua-et-Barbuda", False),
    ("SA", "Saudi Arabia", "Arabie saoudite", False),
    ("AR", "Argentina", "Argentine", False),
    ("AM", "Armenia", "Arménie", False),
    ("AW", "Aruba", "Aruba", False),
    ("AU", "Australia", "Australie", False),
    ("XX", "Other", "Autre / non précisé", False),
    ("AT", "Austria", "Autriche", False),
    ("AZ", "Azerbaijan", "Azerbaïdjan", False),
    ("BS", "Bahamas", "Bahamas", False),
    ("BH", "Bahrain", "Bahreïn", False),
    ("BD", "Bangladesh", "Bangladesh", False),
    ("BB", "Barbados", "Barbade", False),
    ("BE", "Belgium", "Belgique", False),
    ("BZ", "Belize", "Belize", False),
    ("BM", "Bermuda", "Bermudes", False),
    ("BT", "Bhutan", "Bhoutan", False),
    ("BY", "Belarus", "Biélorussie", False),
    ("BO", "Bolivia", "Bolivie", False),
    ("BQ", "Bonaire", "Bonaire", False),
    ("BA", "Bosnia and Herzegovina", "Bosnie-Herzégovine", False),
    ("BW", "Botswana", "Botswana", True),
    ("BN", "Brunei", "Brunei", False),
    ("BR", "Brazil", "Brésil", False),
    ("BG", "Bulgaria", "Bulgarie", False),
    ("BF", "Burkina Faso", "Burkina Faso", True),
    ("BI", "Burundi", "Burundi", True),
    ("BJ", "Benin", "Bénin", True),
    ("KH", "Cambodia", "Cambodge", False),
    ("CM", "Cameroon", "Cameroun", True),
    ("CA", "Canada", "Canada", False),
    ("CV", "Cabo Verde", "Cap-Vert", True),
    ("CL", "Chile", "Chili", False),
    ("CN", "China", "Chine", False),
    ("CY", "Cyprus", "Chypre", False),
    ("CO", "Colombia", "Colombie", False),
    ("KM", "Comoros", "Comores", True),
    ("CG", "Congo", "Congo", True),
    ("KP", "North Korea", "Corée du Nord", False),
    ("KR", "South Korea", "Corée du Sud", False),
    ("CR", "Costa Rica", "Costa Rica", False),
    ("HR", "Croatia", "Croatie", False),
    ("CU", "Cuba", "Cuba", False),
    ("CW", "Curaçao", "Curaçao", False),
    ("CI", "Côte d'Ivoire", "Côte d'Ivoire", True),
    ("DK", "Denmark", "Danemark", False),
    ("DJ", "Djibouti", "Djibouti", True),
    ("DM", "Dominica", "Dominique", False),
    ("ES", "Spain", "Espagne", False),
    ("EE", "Estonia", "Estonie", False),
    ("SZ", "Eswatini", "Eswatini", True),
    ("FJ", "Fiji", "Fidji", False),
    ("FI", "Finland", "Finlande", False),
    ("FR", "France", "France", False),
    ("GA", "Gabon", "Gabon", True),
    ("GM", "Gambia", "Gambie", True),
    ("GH", "Ghana", "Ghana", True),
    ("GI", "Gibraltar", "Gibraltar", False),
    ("GD", "Grenada", "Grenade", False),
    ("GL", "Greenland", "Groenland", False),
    ("GR", "Greece", "Grèce", False),
    ("GP", "Guadeloupe", "Guadeloupe", False),
    ("GU", "Guam", "Guam", False),
    ("GT", "Guatemala", "Guatemala", False),
    ("GG", "Guernsey", "Guernesey", False),
    ("GN", "Guinea", "Guinée", True),
    ("GQ", "Equatorial Guinea", "Guinée équatoriale", True),
    ("GW", "Guinea-Bissau", "Guinée-Bissau", True),
    ("GY", "Guyana", "Guyana", False),
    ("GF", "French Guiana", "Guyane française", False),
    ("GE", "Georgia", "Géorgie", False),
    ("GS", "South Georgia", "Géorgie du Sud", False),
    ("HT", "Haiti", "Haïti", False),
    ("HN", "Honduras", "Honduras", False),
    ("HK", "Hong Kong", "Hong Kong", False),
    ("HU", "Hungary", "Hongrie", False),
    ("IN", "India", "Inde", False),
    ("ID", "Indonesia", "Indonésie", False),
    ("IQ", "Iraq", "Irak", False),
    ("IR", "Iran", "Iran", False),
    ("IE", "Ireland", "Irlande", False),
    ("IS", "Iceland", "Islande", False),
    ("IL", "Israel", "Israël", False),
    ("IT", "Italy", "Italie", False),
    ("JM", "Jamaica", "Jamaïque", False),
    ("JP", "Japan", "Japon", False),
    ("JE", "Jersey", "Jersey", False),
    ("JO", "Jordan", "Jordanie", False),
    ("KZ", "Kazakhstan", "Kazakhstan", False),
    ("KE", "Kenya", "Kenya", True),
    ("KG", "Kyrgyzstan", "Kirghizistan", False),
    ("KI", "Kiribati", "Kiribati", False),
    ("KW", "Kuwait", "Koweït", False),
    ("RE", "Réunion", "La Réunion", True),
    ("LA", "Laos", "Laos", False),
    ("LS", "Lesotho", "Lesotho", True),
    ("LV", "Latvia", "Lettonie", False),
    ("LB", "Lebanon", "Liban", False),
    ("LY", "Libya", "Libye", True),
    ("LR", "Liberia", "Libéria", True),
    ("LI", "Liechtenstein", "Liechtenstein", False),
    ("LT", "Lithuania", "Lituanie", False),
    ("LU", "Luxembourg", "Luxembourg", False),
    ("MO", "Macao", "Macao", False),
    ("MK", "North Macedonia", "Macédoine du Nord", False),
    ("MG", "Madagascar", "Madagascar", True),
    ("MY", "Malaysia", "Malaisie", False),
    ("MW", "Malawi", "Malawi", True),
    ("MV", "Maldives", "Maldives", False),
    ("ML", "Mali", "Mali", True),
    ("MT", "Malta", "Malte", False),
    ("MA", "Morocco", "Maroc", True),
    ("MQ", "Martinique", "Martinique", False),
    ("MU", "Mauritius", "Maurice", True),
    ("MR", "Mauritania", "Mauritanie", True),
    ("YT", "Mayotte", "Mayotte", True),
    ("MX", "Mexico", "Mexique", False),
    ("FM", "Micronesia", "Micronésie", False),
    ("MD", "Moldova", "Moldavie", False),
    ("MC", "Monaco", "Monaco", False),
    ("MN", "Mongolia", "Mongolie", False),
    ("MS", "Montserrat", "Montserrat", False),
    ("ME", "Montenegro", "Monténégro", False),
    ("MZ", "Mozambique", "Mozambique", True),
    ("MM", "Myanmar", "Myanmar", False),
    ("NA", "Namibia", "Namibie", True),
    ("NR", "Nauru", "Nauru", False),
    ("NI", "Nicaragua", "Nicaragua", False),
    ("NE", "Niger", "Niger", True),
    ("NG", "Nigeria", "Nigeria", True),
    ("NU", "Niue", "Niue", False),
    ("NO", "Norway", "Norvège", False),
    ("NC", "New Caledonia", "Nouvelle-Calédonie", False),
    ("NZ", "New Zealand", "Nouvelle-Zélande", False),
    ("NP", "Nepal", "Népal", False),
    ("OM", "Oman", "Oman", False),
    ("UG", "Uganda", "Ouganda", True),
    ("UZ", "Uzbekistan", "Ouzbékistan", False),
    ("PK", "Pakistan", "Pakistan", False),
    ("PW", "Palau", "Palaos", False),
    ("PS", "Palestine", "Palestine", False),
    ("PA", "Panama", "Panama", False),
    ("PG", "Papua New Guinea", "Papouasie-Nouvelle-Guinée", False),
    ("PY", "Paraguay", "Paraguay", False),
    ("NL", "Netherlands", "Pays-Bas", False),
    ("PH", "Philippines", "Philippines", False),
    ("PN", "Pitcairn", "Pitcairn", False),
    ("PL", "Poland", "Pologne", False),
    ("PF", "French Polynesia", "Polynésie française", False),
    ("PR", "Puerto Rico", "Porto Rico", False),
    ("PT", "Portugal", "Portugal", False),
    ("PE", "Peru", "Pérou", False),
    ("QA", "Qatar", "Qatar", False),
    ("CD", "DR Congo", "RD Congo", True),
    ("RO", "Romania", "Roumanie", False),
    ("GB", "United Kingdom", "Royaume-Uni", False),
    ("RU", "Russia", "Russie", False),
    ("RW", "Rwanda", "Rwanda", True),
    ("CF", "Central African Republic", "République centrafricaine", True),
    ("DO", "Dominican Republic", "République dominicaine", False),
    ("EH", "Western Sahara", "Sahara occidental", True),
    ("BL", "Saint Barthélemy", "Saint-Barthélemy", False),
    ("KN", "Saint Kitts and Nevis", "Saint-Kitts-et-Nevis", False),
    ("SM", "San Marino", "Saint-Marin", False),
    ("MF", "Saint Martin", "Saint-Martin", False),
    ("SX", "Sint Maarten", "Saint-Martin (Pays-Bas)", False),
    ("PM", "Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon", False),
    ("VC", "Saint Vincent", "Saint-Vincent-et-les-Grenadines", False),
    ("SH", "Saint Helena", "Sainte-Hélène", True),
    ("LC", "Saint Lucia", "Sainte-Lucie", False),
    ("SV", "El Salvador", "Salvador", False),
    ("WS", "Samoa", "Samoa", False),
    ("AS", "American Samoa", "Samoa américaines", False),
    ("RS", "Serbia", "Serbie", False),
    ("SC", "Seychelles", "Seychelles", True),
    ("SL", "Sierra Leone", "Sierra Leone", True),
    ("SG", "Singapore", "Singapour", False),
    ("SK", "Slovakia", "Slovaquie", False),
    ("SI", "Slovenia", "Slovénie", False),
    ("SO", "Somalia", "Somalie", True),
    ("SD", "Sudan", "Soudan", True),
    ("SS", "South Sudan", "Soudan du Sud", True),
    ("LK", "Sri Lanka", "Sri Lanka", False),
    ("CH", "Switzerland", "Suisse", False),
    ("SR", "Suriname", "Suriname", False),
    ("SE", "Sweden", "Suède", False),
    ("SJ", "Svalbard", "Svalbard", False),
    ("SY", "Syria", "Syrie", False),
    ("ST", "São Tomé and Príncipe", "São Tomé-et-Príncipe", True),
    ("SN", "Senegal", "Sénégal", True),
    ("TJ", "Tajikistan", "Tadjikistan", False),
    ("TZ", "Tanzania", "Tanzanie", True),
    ("TW", "Taiwan", "Taïwan", False),
    ("TD", "Chad", "Tchad", True),
    ("CZ", "Czechia", "Tchéquie", False),
    ("TF", "French Southern Territories", "Terres australes françaises", False),
    ("IO", "British Indian Ocean Territory", "Territoire britannique de l'océan Indien", False),
    ("TH", "Thailand", "Thaïlande", False),
    ("TL", "Timor-Leste", "Timor oriental", False),
    ("TG", "Togo", "Togo", True),
    ("TK", "Tokelau", "Tokelau", False),
    ("TO", "Tonga", "Tonga", False),
    ("TT", "Trinidad and Tobago", "Trinité-et-Tobago", False),
    ("TN", "Tunisia", "Tunisie", True),
    ("TM", "Turkmenistan", "Turkménistan", False),
    ("TR", "Turkey", "Turquie", False),
    ("TV", "Tuvalu", "Tuvalu", False),
    ("UA", "Ukraine", "Ukraine", False),
    ("UY", "Uruguay", "Uruguay", False),
    ("VU", "Vanuatu", "Vanuatu", False),
    ("VA", "Holy See", "Vatican", False),
    ("VE", "Venezuela", "Venezuela", False),
    ("VN", "Vietnam", "Viêt Nam", False),
    ("WF", "Wallis and Futuna", "Wallis-et-Futuna", False),
    ("YE", "Yemen", "Yémen", False),
    ("ZM", "Zambia", "Zambie", True),
    ("ZW", "Zimbabwe", "Zimbabwe", True),
    ("AX", "Åland Islands", "Åland", False),
    ("EG", "Egypt", "Égypte", True),
    ("AE", "United Arab Emirates", "Émirats arabes unis", False),
    ("EC", "Ecuador", "Équateur", False),
    ("ER", "Eritrea", "Érythrée", True),
    ("US", "United States", "États-Unis", False),
    ("ET", "Ethiopia", "Éthiopie", True),
    ("BV", "Bouvet Island", "Île Bouvet", False),
    ("CX", "Christmas Island", "Île Christmas", False),
    ("NF", "Norfolk Island", "Île Norfolk", False),
    ("IM", "Isle of Man", "Île de Man", False),
    ("KY", "Cayman Islands", "Îles Caïmans", False),
    ("CC", "Cocos Islands", "Îles Cocos", False),
    ("CK", "Cook Islands", "Îles Cook", False),
    ("FO", "Faroe Islands", "Îles Féroé", False),
    ("HM", "Heard Island", "Îles Heard-et-MacDonald", False),
    ("FK", "Falkland Islands", "Îles Malouines", False),
    ("MP", "Northern Mariana Islands", "Îles Mariannes du Nord", False),
    ("MH", "Marshall Islands", "Îles Marshall", False),
    ("SB", "Solomon Islands", "Îles Salomon", False),
    ("TC", "Turks and Caicos", "Îles Turques-et-Caïques", False),
    ("VI", "Virgin Islands (US)", "Îles Vierges américaines", False),
    ("VG", "Virgin Islands (UK)", "Îles Vierges britanniques", False),
    ("UM", "US Minor Outlying Islands", "Îles mineures éloignées des États-Unis", False),
]

AFRICAN_COUNTRY_CODES = frozenset({
    "AO",
    "BF",
    "BI",
    "BJ",
    "BW",
    "CD",
    "CF",
    "CG",
    "CI",
    "CM",
    "CV",
    "DJ",
    "DZ",
    "EG",
    "EH",
    "ER",
    "ET",
    "GA",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GW",
    "KE",
    "KM",
    "LR",
    "LS",
    "LY",
    "MA",
    "MG",
    "ML",
    "MR",
    "MU",
    "MW",
    "MZ",
    "NA",
    "NE",
    "NG",
    "RE",
    "RW",
    "SC",
    "SD",
    "SH",
    "SL",
    "SN",
    "SO",
    "SS",
    "ST",
    "SZ",
    "TD",
    "TG",
    "TN",
    "TZ",
    "UG",
    "YT",
    "ZA",
    "ZM",
    "ZW",
})

VALID_COUNTRY_CODES = frozenset(c[0] for c in WORLD_COUNTRIES)

def country_flag(code: str) -> str:
    if not code or code == "XX" or len(code) != 2:
        return "🌍"
    return chr(0x1F1E6 + ord(code[0]) - ord('A')) + chr(0x1F1E6 + ord(code[1]) - ord('A'))
