# Generated by Django 5.2.16 on 2026-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('default_duration_ms', models.PositiveIntegerField(default=5500, help_text="Durée d'affichage par défaut (ms) si la diapo n'en définit pas.")),
                ('pause_on_hover', models.BooleanField(default=True)),
                ('show_dots', models.BooleanField(default=True)),
                ('show_arrows', models.BooleanField(default=True)),
                ('max_height_px', models.PositiveIntegerField(default=140)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages carrousel',
                'verbose_name_plural': 'Réglages carrousel',
            },
        ),
        migrations.AddField(
            model_name='adslide',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texte alternatif accessibilité (sinon titre).', max_length=255),
        ),
        migrations.AddField(
            model_name='adslide',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adslide',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text="Durée d'affichage de cette diapo (ms). Vide = réglage global.", null=True),
        ),
        migrations.AddField(
            model_name='adslide',
            name='impression_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adslide',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes admin (non publiques).'),
        ),
        migrations.AddField(
            model_name='adslide',
            name='open_in_new_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adslide',
            name='sponsor_label',
            field=models.CharField(blank=True, help_text='Libellé sponsor affiché en badge (optionnel).', max_length=120),
        ),
    ]
