# Generated by Django 5.2.16 on 2026-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_shared_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsession',
            name='current_fen',
            field=models.CharField(default='startpos', max_length=120),
        ),
    ]
