# Generated by Django 5.2.16 on 2026-07-12 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_classroom_fen_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='PracticeStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('lichess_id', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(default='lichess', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='learning.practicesection')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('section', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PracticeChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('fen', models.CharField(max_length=120)),
                ('pgn', models.TextField(blank=True)),
                ('solution_uci', models.JSONField(default=list, help_text='Main-line UCI moves')),
                ('goal', models.CharField(choices=[('mate', 'Mate'), ('mateIn', 'Mate in N'), ('drawIn', 'Draw in N'), ('evalIn', 'Eval'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('goal_moves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learning.practicestudy')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_moves', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='learning.practicechapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-completed_at'], name='learning_pr_user_id_fd54a3_idx')],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
