"""
Catalogue des 100 bots AFRICHESS — légendes (ELO élevé) + personnages fictifs (ELO bas).

Chaque bot a un avatar_id unique → /avatars/bots/{avatar_id}.png
"""

from __future__ import annotations

from typing import TypedDict


class BotSpec(TypedDict):
    slug: str
    name: str
    name_en: str
    country: str
    elo: int
    avatar_id: str
    personality: str
    opening_style: str
    description: str
    description_en: str
    is_premium: bool
    is_legend: bool


def _legend(
    slug: str,
    name: str,
    name_en: str,
    country: str,
    elo: int,
    personality: str,
    opening: str,
    desc_fr: str,
    desc_en: str,
) -> BotSpec:
    return {
        "slug": slug,
        "name": name,
        "name_en": name_en,
        "country": country,
        "elo": elo,
        "avatar_id": slug,
        "personality": personality,
        "opening_style": opening,
        "description": desc_fr,
        "description_en": desc_en,
        "is_premium": elo >= 2400,
        "is_legend": True,
    }


def _fictional(
    slug: str,
    name: str,
    name_en: str,
    country: str,
    elo: int,
    personality: str,
    opening: str,
    desc_fr: str,
    desc_en: str,
) -> BotSpec:
    return {
        "slug": slug,
        "name": name,
        "name_en": name_en,
        "country": country,
        "elo": elo,
        "avatar_id": slug,
        "personality": personality,
        "opening_style": opening,
        "description": desc_fr,
        "description_en": desc_en,
        "is_premium": False,
        "is_legend": False,
    }


# ── 30 LÉGENDES (2400–3200 ELO) ─────────────────────────────────────────────

LEGENDS: list[BotSpec] = [
    _legend(
        "magnus-carlsen",
        "Magnus Carlsen",
        "Magnus Carlsen",
        "NO",
        3200,
        "positional",
        "Ruy Lopez",
        "Le GOAT norvégien. Précision machine, finales implacables.",
        "The Norwegian GOAT. Machine-like precision, ruthless endgames.",
    ),
    _legend(
        "hikaru-nakamura",
        "Hikaru Nakamura",
        "Hikaru Nakamura",
        "US",
        3180,
        "tactical",
        "Sicilienne Najdorf",
        "Maître du blitz et des complications. Vitesse + calcul.",
        "Blitz and complications master. Speed plus calculation.",
    ),
    _legend(
        "julien-song",
        "Julien Song",
        "Julien Song",
        "FR",
        3100,
        "creative",
        "Gambit de la Dame",
        "Grand maître français, streamer et tacticien audacieux.",
        "French grandmaster, streamer and bold tactician.",
    ),
    _legend(
        "maxime-keli",
        "Maxime Keli",
        "Maxime Keli",
        "SN",
        3050,
        "aggressive",
        "Attaque king-side",
        "Créateur d'AFRICHESS. Attaque directe, vision globale du jeu.",
        "AFRICHESS creator. Direct attacks, global chess vision.",
    ),
    _legend(
        "joachim-mouhamad",
        "Joachim Mouhamad",
        "Joachim Mouhamad",
        "CM",
        3000,
        "solid",
        "Est-indienne",
        "Champion camerounais. Défense solide, contre-attaque chirurgicale.",
        "Cameroonian champion. Solid defense, surgical counterattack.",
    ),
    _legend(
        "bassem-amin",
        "Bassem Amin",
        "Bassem Amin",
        "EG",
        2950,
        "positional",
        "Dame indienne",
        "Grand maître égyptien, référence africaine du jeu positionnel.",
        "Egyptian grandmaster, Africa's positional reference.",
    ),
    _legend(
        "kenny-solomon",
        "Kenny Solomon",
        "Kenny Solomon",
        "ZA",
        2920,
        "tactical",
        "Sicilienne",
        "Premier GM d'Afrique australe. Tactique pure et instinct de chasseur.",
        "Southern Africa's first GM. Pure tactics and hunter instinct.",
    ),
    _legend(
        "ahmed-adly",
        "Ahmed Adly",
        "Ahmed Adly",
        "EG",
        2900,
        "creative",
        "Grünfeld",
        "Champion du monde junior 2007. Créativité égyptienne légendaire.",
        "2007 World Junior Champion. Legendary Egyptian creativity.",
    ),
    _legend(
        "thomas-sankara",
        "Thomas Sankara",
        "Thomas Sankara",
        "BF",
        2880,
        "aggressive",
        "Gambit du roi",
        "Révolutionnaire burkinabè. Attaque sans compromis, sacrifice pour l'idéal.",
        "Burkinabè revolutionary. Uncompromising attack, sacrifice for ideals.",
    ),
    _legend(
        "nelson-mandela",
        "Nelson Mandela",
        "Nelson Mandela",
        "ZA",
        2850,
        "solid",
        "Est-indienne",
        "Patience légendaire. Défense tenace, victoire par endurance.",
        "Legendary patience. Tenacious defense, victory through endurance.",
    ),
    _legend(
        "malcolm-x",
        "Malcolm X",
        "Malcolm X",
        "US",
        2820,
        "tactical",
        "Contre-attaque",
        "Orateur et stratège. Coups tranchants, riposte immédiate.",
        "Orator and strategist. Sharp moves, immediate riposte.",
    ),
    _legend(
        "patrice-lumumba",
        "Patrice Lumumba",
        "Patrice Lumumba",
        "CD",
        2800,
        "positional",
        "Partie ouverte",
        "Vision panafricaine. Contrôle du centre, plan long terme.",
        "Pan-African vision. Center control, long-term plan.",
    ),
    _legend(
        "kwame-nkrumah",
        "Kwame Nkrumah",
        "Kwame Nkrumah",
        "GH",
        2780,
        "creative",
        "Réti",
        "Père de l'indépendance ghanéenne. Ouvertures modernes, surprise.",
        "Father of Ghanaian independence. Modern openings, surprise.",
    ),
    _legend(
        "mansa-musa",
        "Mansa Musa",
        "Mansa Musa",
        "ML",
        2760,
        "positional",
        "Colle",
        "Empereur du Mali. Domination économique du plateau, patience d'or.",
        "Mali emperor. Economic board domination, golden patience.",
    ),
    _legend(
        "queen-nzinga",
        "Reine Nzinga",
        "Queen Nzinga",
        "AO",
        2740,
        "aggressive",
        "Gambit Evans",
        "Reine guerrière angolaise. Attaque féroce, jamais en retrait.",
        "Angolan warrior queen. Fierce attack, never retreats.",
    ),
    _legend(
        "albert-einstein",
        "Albert Einstein",
        "Albert Einstein",
        "DE",
        2720,
        "creative",
        "Gambit Evans",
        "Génie de la relativité. Coups contre-intuitifs, beauté théorique.",
        "Relativity genius. Counter-intuitive moves, theoretical beauty.",
    ),
    _legend(
        "robert-oppenheimer",
        "Robert Oppenheimer",
        "Robert Oppenheimer",
        "US",
        2700,
        "tactical",
        "Sicilienne Dragon",
        "Père de la bombe atomique. Explosions tactiques, calcul profond.",
        "Father of the atomic bomb. Tactical explosions, deep calculation.",
    ),
    _legend(
        "amon-simutowe",
        "Amon Simutowe",
        "Amon Simutowe",
        "ZM",
        2680,
        "solid",
        "Caro-Kann",
        "Premier GM zambien. Solide comme les Victoria Falls.",
        "Zambia's first GM. Solid as Victoria Falls.",
    ),
    _legend(
        "desmond-tutu",
        "Desmond Tutu",
        "Desmond Tutu",
        "ZA",
        2660,
        "solid",
        "London System",
        "Archbishop et Nobel. Paix sur l'échiquier, mais fermeté en finale.",
        "Archbishop and Nobel laureate. Peace on board, firmness in endgame.",
    ),
    _legend(
        "miriam-makeba",
        "Miriam Makeba",
        "Miriam Makeba",
        "ZA",
        2640,
        "creative",
        "Flank ouvert",
        "Mama Africa. Rythme imprevisible, harmonie dans le chaos.",
        "Mama Africa. Unpredictable rhythm, harmony in chaos.",
    ),
    _legend(
        "chinua-achebe",
        "Chinua Achebe",
        "Chinua Achebe",
        "NG",
        2620,
        "positional",
        "Est-indienne",
        "Géant de la littérature. Chaque coup raconte une histoire.",
        "Literary giant. Every move tells a story.",
    ),
    _legend(
        "wole-soyinka",
        "Wole Soyinka",
        "Wole Soyinka",
        "NG",
        2600,
        "creative",
        "Anglaise",
        "Nobel de littérature. Théâtre sur l'échiquier, pièges dramatiques.",
        "Literature Nobel. Theater on the board, dramatic traps.",
    ),
    _legend(
        "cheikh-anta-diop",
        "Cheikh Anta Diop",
        "Cheikh Anta Diop",
        "SN",
        2580,
        "positional",
        "Réti",
        "Historien sénégalais. Analyse profonde, refonte des structures.",
        "Senegalese historian. Deep analysis, structural refounding.",
    ),
    _legend(
        "leopold-senghor",
        "Léopold Sédar Senghor",
        "Léopold Sédar Senghor",
        "SN",
        2560,
        "creative",
        "Est-indienne",
        "Poète-président. Négritude et élégance sur les 64 cases.",
        "Poet-president. Négritude and elegance on 64 squares.",
    ),
    _legend(
        "haile-selassie",
        "Haile Selassie",
        "Haile Selassie",
        "ET",
        2540,
        "solid",
        "Est-indienne",
        "Empereur éthiopien. Majesté, structure et longue durée.",
        "Ethiopian emperor. Majesty, structure and longevity.",
    ),
    _legend(
        "ahmed-sekou-toure",
        "Ahmed Sékou Touré",
        "Ahmed Sékou Touré",
        "GN",
        2520,
        "aggressive",
        "Gambit du roi",
        "Leader guinéen. Indépendance par la pression constante.",
        "Guinean leader. Independence through constant pressure.",
    ),
    _legend(
        "marie-curie",
        "Marie Curie",
        "Marie Curie",
        "PL",
        2500,
        "tactical",
        "Sicilienne",
        "Double Nobel. Précision radiologique, découvertes tactiques.",
        "Double Nobel. Radiological precision, tactical discoveries.",
    ),
    _legend(
        "ada-lovelace",
        "Ada Lovelace",
        "Ada Lovelace",
        "GB",
        2480,
        "creative",
        "Gambit de la Dame",
        "Première programmeuse. Algorithmes avant l'heure sur l'échiquier.",
        "First programmer. Algorithms ahead of time on the board.",
    ),
    _legend(
        "frida-kahlo",
        "Frida Kahlo",
        "Frida Kahlo",
        "MX",
        2460,
        "creative",
        "Benoni",
        "Artiste mexicaine. Coups colorés, douleur transformée en victoire.",
        "Mexican artist. Colorful moves, pain transformed into victory.",
    ),
]

# ── 70 PERSONNAGES FICTIFS (400–2200 ELO) ────────────────────────────────────

_FICT = [
    ("Yao Kouassi", "Yao Kouassi", "CI", "aggressive", "Sicilienne"),
    ("Aïcha Traoré", "Aisha Traore", "ML", "tactical", "Gambit de la Dame"),
    ("Samuel Okoye", "Samuel Okoye", "NG", "solid", "Caro-Kann"),
    ("Fatoumata Diallo", "Fatoumata Diallo", "GN", "positional", "Est-indienne"),
    ("Thabo Mthembu", "Thabo Mthembu", "ZA", "endgame", "Partie ouverte"),
    ("Zara Mwangi", "Zara Mwangi", "KE", "creative", "Réti"),
    ("Ibrahim Sow", "Ibrahim Sow", "SN", "aggressive", "Gambit du roi"),
    ("Naledi Khumalo", "Naledi Khumalo", "ZA", "tactical", "Scandinave"),
    ("Kofi Mensah", "Kofi Mensah", "GH", "solid", "London System"),
    ("Amara Okafor", "Amara Okafor", "NG", "positional", "Dame indienne"),
    ("Moussa Keita", "Moussa Keita", "ML", "aggressive", "Alekhine"),
    ("Nia Banda", "Nia Banda", "ZM", "creative", "Anglaise"),
    ("Cheikh Ba", "Cheikh Ba", "SN", "solid", "Est-indienne"),
    ("Diarra Camara", "Diarra Camara", "GN", "tactical", "Sicilienne"),
    ("Lerato Ndlovu", "Lerato Ndlovu", "ZA", "endgame", "Partie fermée"),
    ("Jabari Hassan", "Jabari Hassan", "TZ", "aggressive", "Gambit Evans"),
    ("Zola Nkosi", "Zola Nkosi", "ZA", "creative", "Benoni"),
    ("Adama Fofana", "Adama Fofana", "CI", "positional", "Colle"),
    ("Binta Sow", "Binta Sow", "SN", "solid", "Caro-Kann"),
    ("Chidi Eze", "Chidi Eze", "NG", "tactical", "Sicilienne"),
    ("Dalia Moyo", "Dalia Moyo", "ZW", "creative", "Flank ouvert"),
    ("Esi Ampofo", "Esi Ampofo", "GH", "positional", "Réti"),
    ("Femi Adeyemi", "Femi Adeyemi", "NG", "aggressive", "Attaque king-side"),
    ("Gugu Dlamini", "Gugu Dlamini", "ZA", "solid", "Est-indienne"),
    ("Hassan Omar", "Hassan Omar", "KE", "tactical", "Contre-attaque"),
    ("Imani Juma", "Imani Juma", "TZ", "creative", "Gambit de la Dame"),
    ("Jengo Mabaso", "Jengo Mabaso", "ZA", "endgame", "Partie ouverte"),
    ("Kesi Mutombo", "Kesi Mutombo", "CD", "aggressive", "Gambit du roi"),
    ("Lamine Diop", "Lamine Diop", "SN", "positional", "Dame indienne"),
    ("Makena Wanjiru", "Makena Wanjiru", "KE", "solid", "London System"),
    ("Ngozi Okonkwo", "Ngozi Okonkwo", "NG", "tactical", "Sicilienne"),
    ("Olu Chukwu", "Olu Chukwu", "NG", "creative", "Anglaise"),
    ("Pendo Akinyi", "Pendo Akinyi", "KE", "positional", "Est-indienne"),
    ("Rashid Bah", "Rashid Bah", "GM", "aggressive", "Alekhine"),
    ("Sanaa Mbeki", "Sanaa Mbeki", "ZA", "solid", "Caro-Kann"),
    ("Tendai Muzenda", "Tendai Muzenda", "ZW", "endgame", "Partie fermée"),
    ("Umi Abdi", "Umi Abdi", "SO", "tactical", "Scandinave"),
    ("Wanjiku Kamau", "Wanjiku Kamau", "KE", "creative", "Réti"),
    ("Xolani Ndebele", "Xolani Ndebele", "ZA", "aggressive", "Gambit Evans"),
    ("Yaa Asantewaa", "Yaa Asantewaa", "GH", "positional", "Partie ouverte"),
    ("Zuberi Mwangi", "Zuberi Mwangi", "KE", "solid", "Est-indienne"),
    ("Abeni Osei", "Abeni Osei", "GH", "tactical", "Sicilienne"),
    ("Chidinma Okoro", "Chidinma Okoro", "NG", "creative", "Benoni"),
    ("Doudou Fall", "Doudou Fall", "SN", "aggressive", "Gambit du roi"),
    ("Efua Boateng", "Efua Boateng", "GH", "positional", "Colle"),
    ("Farida Benali", "Farida Benali", "MA", "solid", "Caro-Kann"),
    ("Gorgui Ndiaye", "Gorgui Ndiaye", "SN", "tactical", "Contre-attaque"),
    ("Habiba Said", "Habiba Said", "EG", "creative", "Gambit de la Dame"),
    ("Issa Koné", "Issa Koné", "ML", "endgame", "Partie ouverte"),
    ("Jemila Toure", "Jemila Toure", "CI", "aggressive", "Alekhine"),
    ("Karim El Amrani", "Karim El Amrani", "MA", "positional", "Dame indienne"),
    ("Laila Benjelloun", "Laila Benjelloun", "MA", "solid", "London System"),
    ("Mamadou Barry", "Mamadou Barry", "GN", "tactical", "Sicilienne"),
    ("Ndeye Fall", "Ndeye Fall", "SN", "creative", "Flank ouvert"),
    ("Oumar Sy", "Oumar Sy", "SN", "aggressive", "Gambit Evans"),
    ("Pascaline Uwimana", "Pascaline Uwimana", "RW", "positional", "Est-indienne"),
    ("Quincy Addo", "Quincy Addo", "GH", "solid", "Caro-Kann"),
    ("Ramatou Diagne", "Ramatou Diagne", "SN", "tactical", "Scandinave"),
    ("Sekou Doumbia", "Sekou Doumbia", "ML", "endgame", "Partie fermée"),
    ("Tafari Makonnen", "Tafari Makonnen", "ET", "creative", "Réti"),
    ("Uche Nwankwo", "Uche Nwankwo", "NG", "aggressive", "Attaque king-side"),
    ("Véronique Mbaye", "Véronique Mbaye", "SN", "positional", "Colle"),
    ("Wassim Ben Salah", "Wassim Ben Salah", "TN", "solid", "Est-indienne"),
    ("Xena Mokoena", "Xena Mokoena", "ZA", "tactical", "Sicilienne"),
    ("Youssef Alami", "Youssef Alami", "MA", "creative", "Anglaise"),
    ("Zainab Hussein", "Zainab Hussein", "KE", "aggressive", "Gambit du roi"),
    ("Ablaye Diagne", "Ablaye Diagne", "SN", "solid", "London System"),
    ("Boubacar Sall", "Boubacar Sall", "SN", "positional", "Dame indienne"),
    ("Coumba Gueye", "Coumba Gueye", "SN", "tactical", "Contre-attaque"),
    ("Djibril Ndiaye", "Djibril Ndiaye", "SN", "creative", "Benoni"),
    ("Elsa Koffi", "Elsa Koffi", "CI", "endgame", "Partie ouverte"),
]

FICTIONAL: list[BotSpec] = []
for i, (name, name_en, country, pers, opening) in enumerate(_FICT):
    elo = 400 + i * 26  # 400 → ~2194
    slug = f"bot-{i + 31:03d}"
    pers_fr = {"aggressive": "agressif", "tactical": "tactique", "solid": "solide", "positional": "positionnel", "creative": "créatif", "endgame": "finale"}.get(pers, pers)
    FICTIONAL.append(
        _fictional(
            slug,
            name,
            name_en,
            country,
            elo,
            pers,
            opening,
            f"{name} — joueur·euse de club, style {pers_fr} avec la {opening}.",
            f"{name_en} — club player, {pers} style with the {opening}.",
        )
    )

BOT_CATALOG: list[BotSpec] = LEGENDS + FICTIONAL

assert len(BOT_CATALOG) == 100, f"Expected 100 bots, got {len(BOT_CATALOG)}"
