from django.urls import path

from . import broadcast_views, extra_views, fairplay_admin_views, fairplay_views, views

urlpatterns = [
    path("", views.GameListView.as_view(), name="game-list"),
    path("ai/", views.CreateAIGameView.as_view(), name="create-ai-game"),
    path("ai/preview/", views.ai_strength_preview, name="ai-strength-preview"),
    path("tts/", views.speech_tts, name="speech-tts"),
    path("bots/", views.BotListView.as_view(), name="bot-list"),
    path("bots/ladder/", views.BotLadderView.as_view(), name="bot-ladder"),
    path("bots/<slug:slug>/", views.BotDetailView.as_view(), name="bot-detail"),
    path("active/", views.active_games, name="active-games"),
    path("matchmaking/", views.MatchmakingView.as_view(), name="matchmaking"),
    path("matchmaking/status/", views.MatchmakingStatusView.as_view(), name="matchmaking-status"),
    path("challenge/", views.ChallengeUserView.as_view(), name="challenge-user"),
    path("challenges/pending/", views.PendingChallengesView.as_view(), name="challenge-pending"),
    path("challenges/sent/", views.SentChallengesView.as_view(), name="challenge-sent"),
    path("challenges/<int:pk>/", views.ChallengeDetailView.as_view(), name="challenge-detail"),
    path("challenges/<int:pk>/accept/", views.ChallengeAcceptView.as_view(), name="challenge-accept"),
    path("challenges/<int:pk>/decline/", views.ChallengeDeclineView.as_view(), name="challenge-decline"),
    path("challenges/<int:pk>/cancel/", views.ChallengeCancelView.as_view(), name="challenge-cancel"),
    path("live/", views.LiveGamesView.as_view(), name="live-games"),
    path("live/tv/", views.LiveTvView.as_view(), name="live-tv"),
    path("broadcasts/", broadcast_views.BroadcastListCreateView.as_view(), name="broadcast-list"),
    path("broadcasts/<slug:slug>/", broadcast_views.BroadcastDetailView.as_view(), name="broadcast-detail"),
    path("broadcasts/<slug:slug>/sync/", broadcast_views.BroadcastSyncView.as_view(), name="broadcast-sync"),
    path("correspondence/", views.CorrespondenceListView.as_view(), name="correspondence-list"),
    path("correspondence/challenge/", views.CorrespondenceChallengeView.as_view(), name="correspondence-challenge"),
    path("correspondence/seek/", views.CorrespondenceSeekView.as_view(), name="correspondence-seek"),
    path("simul/", extra_views.SimulListCreateView.as_view(), name="simul-list"),
    path("simul/<int:session_id>/", extra_views.SimulDetailView.as_view(), name="simul-detail"),
    path("simul/<int:session_id>/join/", extra_views.SimulJoinView.as_view(), name="simul-join"),
    path("vote/create/", extra_views.VoteGameCreateView.as_view(), name="vote-create"),
    path("<uuid:game_id>/vote/", extra_views.CastVoteView.as_view(), name="vote-cast"),
    path("<uuid:game_id>/vote/status/", extra_views.VoteStatusView.as_view(), name="vote-status"),
    path("<uuid:game_id>/vote/apply/", extra_views.ApplyVoteMoveView.as_view(), name="vote-apply"),
    path("openings/lookup/", views.opening_lookup, name="opening-lookup"),
    path("openings/explorer/", views.lichess_opening_explorer, name="lichess-opening-explorer"),
    path("engine/eval/", views.engine_eval, name="engine-eval"),
    path("engine/tablebase/", views.tablebase_probe, name="engine-tablebase"),
    path("<uuid:id>/", views.GameDetailView.as_view(), name="game-detail"),
    path("<uuid:game_id>/legal-moves/", views.legal_moves, name="game-legal-moves"),
    path("<uuid:game_id>/move/", views.MakeMoveView.as_view(), name="game-move"),
    path("<uuid:game_id>/undo/", views.UndoMoveView.as_view(), name="game-undo"),
    path("<uuid:game_id>/analyze/", views.AnalyzeGameView.as_view(), name="game-analyze"),
    path("<uuid:game_id>/analyze/async/", views.AnalyzeGameAsyncView.as_view(), name="game-analyze-async"),
    path("<uuid:game_id>/analyze/status/", views.AnalyzeGameStatusView.as_view(), name="game-analyze-status"),
    path("<uuid:game_id>/draw/", views.DrawOfferView.as_view(), name="game-draw-offer"),
    path("<uuid:game_id>/draw/respond/", views.DrawRespondView.as_view(), name="game-draw-respond"),
    path("<uuid:game_id>/draw/claim/", views.ClaimDrawView.as_view(), name="game-draw-claim"),
    path("<uuid:game_id>/claim-flag/", views.ClaimFlagView.as_view(), name="game-claim-flag"),
    path("<uuid:game_id>/abort/", views.AbortGameView.as_view(), name="game-abort"),
    path("<uuid:game_id>/resign/", views.ResignGameView.as_view(), name="game-resign"),
    path("<uuid:game_id>/takeback/", views.TakebackOfferView.as_view(), name="game-takeback-offer"),
    path("<uuid:game_id>/takeback/respond/", views.TakebackRespondView.as_view(), name="game-takeback-respond"),
    path("<uuid:game_id>/conditional/", views.ConditionalMoveView.as_view(), name="game-conditional"),
    path("<uuid:game_id>/rematch/", views.RematchView.as_view(), name="game-rematch"),
    path("fairplay/status/", fairplay_views.FairPlayStatusView.as_view(), name="fairplay-status"),
    path("fairplay/consent/", fairplay_views.FairPlayConsentView.as_view(), name="fairplay-consent"),
    path("fairplay/appeals/", fairplay_views.FairPlayAppealView.as_view(), name="fairplay-appeal"),
    path("admin/fairplay/overview/", fairplay_admin_views.AdminFairPlayOverviewView.as_view(), name="admin-fairplay-overview"),
    path("admin/fairplay/queue/", fairplay_admin_views.AdminFairPlayQueueView.as_view(), name="admin-fairplay-queue"),
    path("admin/fairplay/games/<uuid:game_id>/", fairplay_admin_views.AdminFairPlayGameView.as_view(), name="admin-fairplay-game"),
    path("admin/fairplay/users/<int:user_id>/", fairplay_admin_views.AdminFairPlayUserView.as_view(), name="admin-fairplay-user"),
    path("admin/fairplay/cases/<int:case_id>/decide/", fairplay_admin_views.AdminFairPlayDecisionView.as_view(), name="admin-fairplay-decide"),
    path(
        "admin/fairplay/appeals/<int:appeal_id>/resolve/",
        fairplay_admin_views.AdminFairPlayAppealResolveView.as_view(),
        name="admin-fairplay-appeal-resolve",
    ),
]
