"""Drills de fin de partie — catalogue extensible."""

from __future__ import annotations

ENDGAME_DRILLS: list[dict] = [
    {
        "id": "kp_opposition",
        "fen": "8/8/8/8/8/4K3/8/4k3 w - - 0 1",
        "goal_key": "endgame.kp.opposition",
        "solution": ["e3"],
        "theme": "king_pawn",
        "rating": 900,
    },
    {
        "id": "kp_push",
        "fen": "8/8/8/3k4/8/3K4/3P4/8 w - - 0 1",
        "goal_key": "endgame.kp.push",
        "solution": ["d4"],
        "theme": "king_pawn",
        "rating": 950,
    },
    {
        "id": "rook_lift",
        "fen": "6k1/8/8/8/8/8/6PP/6K1 w - - 0 1",
        "goal_key": "endgame.rook.lift",
        "solution": ["g3"],
        "theme": "rook",
        "rating": 1000,
    },
    {
        "id": "rook_back_rank",
        "fen": "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
        "goal_key": "endgame.rook.backRank",
        "solution": ["e1e8"],
        "theme": "rook",
        "rating": 850,
    },
    {
        "id": "queen_vs_king",
        "fen": "8/8/8/8/4K3/8/8/4Q3 w - - 0 1",
        "goal_key": "endgame.queen.deliver",
        "solution": ["e4e5"],
        "theme": "queen",
        "rating": 800,
    },
    {
        "id": "bishop_pair",
        "fen": "8/8/8/8/4k3/8/4B3/4K2B w - - 0 1",
        "goal_key": "endgame.bishop.control",
        "solution": ["e2f3"],
        "theme": "bishop",
        "rating": 1100,
    },
    {
        "id": "knight_fork_end",
        "fen": "8/8/4k3/8/4N3/8/4K3/8 w - - 0 1",
        "goal_key": "endgame.knight.activity",
        "solution": ["e4c5"],
        "theme": "knight",
        "rating": 1050,
    },
    {
        "id": "pawn_race",
        "fen": "8/8/8/8/4K3/8/4P3/4k3 w - - 0 1",
        "goal_key": "endgame.pawn.race",
        "solution": ["e4d5"],
        "theme": "king_pawn",
        "rating": 920,
    },
    {
        "id": "rook_end_cut",
        "fen": "8/8/8/8/8/4K4/4R3/4k3 w - - 0 1",
        "goal_key": "endgame.rook.cut",
        "solution": ["e2e1"],
        "theme": "rook",
        "rating": 980,
    },
    {
        "id": "mate_in_1_back_rank",
        "fen": "6k1/5ppp/8/8/8/5R2/5PPP/6K1 w - - 0 1",
        "goal_key": "endgame.mate.backRank",
        "solution": ["f3f8"],
        "theme": "mate",
        "rating": 750,
    },
    {
        "id": "opposition_black",
        "fen": "8/8/8/8/8/4k3/8/4K3 b - - 0 1",
        "goal_key": "endgame.kp.oppositionBlack",
        "solution": ["e3d3"],
        "theme": "king_pawn",
        "rating": 930,
    },
    {
        "id": "rook_7th",
        "fen": "4k3/8/8/8/8/8/4R3/4K3 w - - 0 1",
        "goal_key": "endgame.rook.seventh",
        "solution": ["e2e7"],
        "theme": "rook",
        "rating": 1020,
    },
]
