import type { StatsPdfLabels } from "./types";

type TranslateFn = (key: string, params?: Record<string, string | number>) => string;

export function buildStatsPdfLabels(t: TranslateFn, locale: string): StatsPdfLabels {
  const dateFmt = new Intl.DateTimeFormat(locale === "fr" ? "fr-FR" : "en-GB", {
    dateStyle: "long",
    timeStyle: "short",
  });

  return {
    brand: "AFRICHESS",
    coverSubtitle: t("stats.pdf.coverSubtitle"),
    coverTagline: t("stats.pdf.coverTagline"),
    generatedFor: t("stats.pdf.generatedFor"),
    generatedAt: dateFmt.format(new Date()),
    page: t("stats.pdf.page"),
    of: t("stats.pdf.of"),
    confidential: t("stats.pdf.confidential"),
    sectionSummary: t("stats.table.summary"),
    sectionOutcomes: t("stats.chart.outcomes"),
    sectionModes: t("stats.table.byMode"),
    sectionOpponents: t("stats.table.opponentColor"),
    sectionRatings: t("stats.table.eloRatings"),
    sectionEloHistory: t("stats.table.eloHistory"),
    sectionRecentGames: t("stats.table.recentGames"),
    sectionOpenings: t("stats.table.openings"),
    sectionActivity: t("stats.table.activity30"),
    games: t("stats.card.games"),
    wins: t("stats.card.wins"),
    winRate: t("stats.table.winRate"),
    streak: t("stats.card.streak"),
    playTime: t("stats.card.playTime"),
    puzzles: t("stats.card.puzzles"),
    vsAi: t("stats.card.vsAi"),
    victories: t("stats.chart.victories"),
    draws: t("stats.chart.draws"),
    losses: t("stats.chart.losses"),
    mode: t("stats.table.mode"),
    played: t("stats.table.played"),
    won: t("stats.table.won"),
    drawn: t("stats.table.drawn"),
    lost: t("stats.table.lost"),
    winPct: t("stats.table.winPct"),
    online: t("stats.chart.online"),
    ai: t("stats.chart.ai"),
    white: t("stats.table.white"),
    black: t("stats.table.black"),
    opponent: t("stats.table.opponent"),
    opening: t("stats.table.opening"),
    result: t("stats.table.result"),
    date: t("stats.table.date"),
    moves: t("stats.table.moves"),
    elo: t("leaderboard.col.elo"),
    peak: t("stats.table.peak"),
    before: t("stats.table.before"),
    after: t("stats.table.after"),
    change: "Δ",
    termination: t("stats.chart.terminations"),
    noData: t("stats.chart.noGames"),
    outcomeWin: t("play.recent.win"),
    outcomeLoss: t("play.recent.loss"),
    outcomeDraw: t("play.recent.draw"),
  };
}
