# Generated by Django 5.2.15 on 2026-06-04 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0002_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournamentround",
            name="games",
            field=models.ManyToManyField(blank=True, to="games.game"),
        ),
        migrations.AddField(
            model_name="tournamentround",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentround",
            unique_together={("tournament", "round_number")},
        ),
    ]
