# Generated by Django 5.2.15 on 2026-06-27 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_level2_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='puzzle',
            new_name='puzzles_puz_is_dail_28282a_idx',
            old_name='puzzles_puz_is_dail_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='puzzle',
            new_name='puzzles_puz_difficu_a751d2_idx',
            old_name='puzzles_puz_difficu_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='puzzleattempt',
            new_name='puzzles_puz_user_id_824f97_idx',
            old_name='puzzles_puz_user_id_7g8h9i_idx',
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['author', 'source'], name='puzzles_puz_author__51d756_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzlerushsession',
            index=models.Index(fields=['user', '-started_at'], name='puzzles_puz_user_id_941d5a_idx'),
        ),
    ]
