# Generated by Django 5.2.15 on 2026-07-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_puzzle_pool_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='puzzle',
            new_name='puzzles_puz_difficu_bbd846_idx',
            old_name='puzzles_puz_diff_rat_idx',
        ),
        migrations.RenameIndex(
            model_name='puzzle',
            new_name='puzzles_puz_source_a8d783_idx',
            old_name='puzzles_puz_source_idx',
        ),
        migrations.AddField(
            model_name='puzzlerushsession',
            name='mode',
            field=models.CharField(choices=[('rush', 'Rush'), ('storm', 'Storm'), ('survival', 'Survival')], default='rush', max_length=20),
        ),
    ]
