from django.urls import path

from . import marketplace_views, report_views, views

urlpatterns = [
    path("friends/", views.FriendsListView.as_view(), name="friends-list"),
    path("friends/pending/", views.PendingFriendsView.as_view(), name="friends-pending"),
    path("friends/sent/", views.SentFriendsView.as_view(), name="friends-sent"),
    path("friends/request/", views.SendFriendRequestView.as_view(), name="friend-request"),
    path("friends/challenge/", views.ChallengeFriendView.as_view(), name="friend-challenge"),
    path("friends/<int:pk>/accept/", views.AcceptFriendView.as_view(), name="friend-accept"),
    path("friends/<int:pk>/decline/", views.DeclineFriendView.as_view(), name="friend-decline"),
    path("friends/<int:pk>/cancel/", views.CancelFriendRequestView.as_view(), name="friend-cancel"),
    path("friends/unfriend/<str:username>/", views.UnfriendView.as_view(), name="friend-unfriend"),
    path("friends/block/<str:username>/", views.BlockUserView.as_view(), name="friend-block"),
    path("users/search/", views.UserSearchView.as_view(), name="user-search"),
    path("users/<str:username>/relationship/", views.UserRelationshipView.as_view(), name="user-relationship"),
    path("users/<str:username>/follow/", views.FollowUserView.as_view(), name="user-follow"),
    path("users/<str:username>/unfollow/", views.UnfollowUserView.as_view(), name="user-unfollow"),
    path("users/me/following/", views.FollowingListView.as_view(), name="my-following"),
    path("users/<str:username>/following/", views.FollowingListView.as_view(), name="user-following"),
    path("users/<str:username>/followers/", views.FollowersListView.as_view(), name="user-followers"),
    path(
        "messages/<str:username>/",
        views.DirectMessageListView.as_view(),
        name="direct-messages",
    ),
    path("clubs/", views.ClubListView.as_view(), name="club-list"),
    path("clubs/<slug:slug>/", views.ClubDetailView.as_view(), name="club-detail"),
    path("clubs/<slug:slug>/join/", views.JoinClubView.as_view(), name="club-join"),
    path("clubs/<slug:slug>/events/", views.ClubEventListCreateView.as_view(), name="club-events"),
    path("clubs/<slug:slug>/arena/", views.ClubArenaChallengeView.as_view(), name="club-arena"),
    path("forum/", views.ForumPostListView.as_view(), name="forum-list"),
    path("forum/<int:pk>/", views.ForumPostDetailView.as_view(), name="forum-detail"),
    path("forum/<int:pk>/comment/", views.ForumCommentCreateView.as_view(), name="forum-comment"),
    path("forum/<int:pk>/like/", views.ForumLikeView.as_view(), name="forum-like"),
    path(
        "chat/<str:room_type>/<str:room_id>/",
        views.ChatHistoryView.as_view(),
        name="chat-history",
    ),
    path(
        "chat/<str:room_type>/<str:room_id>/send/",
        views.PostChatMessageView.as_view(),
        name="chat-send",
    ),
    path("streamers/", marketplace_views.StreamerListView.as_view(), name="streamer-list"),
    path("coaches/", marketplace_views.CoachListView.as_view(), name="coach-list"),
    path("report/", report_views.ReportPlayerView.as_view(), name="player-report"),
    path("events/", report_views.PlatformEventListView.as_view(), name="platform-events"),
]
