# Generated by Django 5.2.15 on 2026-06-04 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for opponent"),
                            ("active", "In progress"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                            ("draw", "Draw"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("bullet", "Bullet (1+0)"),
                            ("blitz", "Blitz (3+2)"),
                            ("rapid", "Rapid (10+0)"),
                            ("classical", "Classical (30+0)"),
                            ("ai", "vs Computer"),
                            ("puzzle", "Puzzle"),
                        ],
                        default="blitz",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-0", "White wins"),
                            ("0-1", "Black wins"),
                            ("1/2-1/2", "Draw"),
                            ("*", "Aborted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=100,
                    ),
                ),
                ("pgn", models.TextField(blank=True)),
                ("move_count", models.PositiveSmallIntegerField(default=0)),
                ("white_time_ms", models.PositiveIntegerField(default=180000)),
                ("black_time_ms", models.PositiveIntegerField(default=180000)),
                ("increment_ms", models.PositiveIntegerField(default=2000)),
                ("is_vs_ai", models.BooleanField(default=False)),
                ("ai_difficulty", models.PositiveSmallIntegerField(default=5)),
                ("termination_reason", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy_white", models.FloatField(blank=True, null=True)),
                ("accuracy_black", models.FloatField(blank=True, null=True)),
                ("blunders_white", models.PositiveSmallIntegerField(default=0)),
                ("blunders_black", models.PositiveSmallIntegerField(default=0)),
                ("best_moves_json", models.JSONField(default=list)),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchmakingQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("bullet", "Bullet (1+0)"),
                            ("blitz", "Blitz (3+2)"),
                            ("rapid", "Rapid (10+0)"),
                            ("classical", "Classical (30+0)"),
                            ("ai", "vs Computer"),
                            ("puzzle", "Puzzle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("elo", models.PositiveIntegerField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_number", models.PositiveSmallIntegerField()),
                ("san", models.CharField(max_length=10)),
                ("uci", models.CharField(max_length=10)),
                ("fen_after", models.CharField(max_length=100)),
                ("played_by_white", models.BooleanField()),
                (
                    "time_remaining_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["move_number", "created_at"],
            },
        ),
    ]
