# Generated by Django 5.2.15 on 2026-06-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_correspondence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='SN', max_length=2)),
                ('elo', models.PositiveIntegerField()),
                ('avatar_id', models.CharField(default='avatar-1', max_length=20)),
                ('personality', models.CharField(blank=True, max_length=50)),
                ('opening_style', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['elo', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='games_game_tournam_677594_idx',
            old_name='games_game_tournam_6a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='games_game_status_93bd1e_idx',
            old_name='games_game_status__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='move',
            new_name='games_move_game_id_ebaa0c_idx',
            old_name='games_move_game_id_4d5e6f_idx',
        ),
        migrations.AddField(
            model_name='game',
            name='chess960_position_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Position Chess960 (0–959)', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('standard', 'Standard'), ('chess960', 'Chess960')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='ai_difficulty',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_timed',
            field=models.BooleanField(default=True, help_text='False = partie sans chronomètre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='5, 10, 15, 20, 25 ou 30 si is_timed', null=True),
        ),
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='mode',
            field=models.CharField(choices=[('bullet', 'Bullet (1+0)'), ('blitz', 'Blitz (3+2)'), ('rapid', 'Rapid (10+0)'), ('classical', 'Classical (30+0)'), ('correspondence', 'Correspondence (daily)'), ('ai', 'vs Computer'), ('puzzle', 'Puzzle')], max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.chessbot'),
        ),
    ]
