# Generated by Django 5.2.15 on 2026-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_chessbot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('standard', 'Standard'), ('chess960', 'Chess960'), ('crazyhouse', 'Crazyhouse')], default='standard', max_length=20),
        ),
    ]
