# Generated by Django 5.2.15 on 2026-06-27 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_level2_extended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchmakingqueue',
            name='games_match_mode_cc85d1_idx',
        ),
        migrations.RenameIndex(
            model_name='correspondencequeue',
            new_name='games_corre_days_pe_bd0529_idx',
            old_name='games_corre_days_elo_idx',
        ),
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('standard', 'Standard'), ('chess960', 'Chess960'), ('crazyhouse', 'Crazyhouse'), ('kingofthehill', 'King of the Hill'), ('threecheck', 'Three-check')], default='standard', max_length=20),
        ),
        migrations.AddIndex(
            model_name='matchmakingqueue',
            index=models.Index(fields=['mode', 'elo', 'is_rated'], name='games_match_mode_25aa76_idx'),
        ),
    ]
