# Generated by Django 5.2.15 on 2026-07-03 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0031_backfill_repetition_counts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mode", models.CharField(default="blitz", max_length=20)),
                ("odds", models.CharField(default="none", max_length=20)),
                ("is_rated", models.BooleanField(default=False)),
                ("is_timed", models.BooleanField(default=True)),
                (
                    "time_control",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("challenger_plays_white", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="fairplayappeal",
            new_name="games_fairp_status_6e9c39_idx",
            old_name="games_fairp_appeal_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayauditlog",
            new_name="games_fairp_action_ec6d09_idx",
            old_name="games_fairp_audit_act_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayauditlog",
            new_name="games_fairp_target__3cd065_idx",
            old_name="games_fairp_audit_tgt_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayintegrityprofile",
            new_name="games_fairp_shadow__dc3e38_idx",
            old_name="games_fairp_shadow__a8c2f1_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayintegrityprofile",
            new_name="games_fairp_trust_s_ab66a4_idx",
            old_name="games_fairp_trust_s_91b4e2_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayreport",
            new_name="games_fairp_verdict_5dc04e_idx",
            old_name="games_fairp_verdict_0d0f8a_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayreviewcase",
            new_name="games_fairp_status_07bf9a_idx",
            old_name="games_fairp_status_8a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayreviewcase",
            new_name="games_fairp_peer_sc_3fb6f9_idx",
            old_name="games_fairp_peer_sc_9d2e3f_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplaysanction",
            new_name="games_fairp_user_id_26f94d_idx",
            old_name="games_fairp_user_ac_4c5d6e_idx",
        ),
        migrations.RenameIndex(
            model_name="fairplayuserconsent",
            new_name="games_fairp_consent_40a559_idx",
            old_name="games_fairp_consent_idx",
        ),
        migrations.RenameIndex(
            model_name="gamefairplaytelemetry",
            new_name="games_gamef_game_id_423ee4_idx",
            old_name="games_gamef_game_id_6f0f8a_idx",
        ),
        migrations.AlterField(
            model_name="fairplayauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view_overview", "View overview"),
                    ("view_queue", "View queue"),
                    ("view_game", "View game"),
                    ("view_user", "View user"),
                    ("decide_case", "Decide case"),
                    ("engine_failure", "Engine failure"),
                    ("sanction_expired", "Sanction expired"),
                    ("appeal_resolved", "Appeal resolved"),
                    ("auto_recommend", "Auto recommend"),
                    ("auto_sanction", "Auto sanction"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="gamechallenge",
            name="challenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamechallenge",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_challenge",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamechallenge",
            name="opponent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="gamechallenge",
            index=models.Index(
                fields=["opponent", "status", "-created_at"],
                name="games_gamec_opponen_44994a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gamechallenge",
            index=models.Index(
                fields=["challenger", "status", "-created_at"],
                name="games_gamec_challen_ff1f01_idx",
            ),
        ),
    ]
