# Generated by Django 5.2.16 on 2026-07-11 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_game_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chessbot',
            name='tier',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('novice', 'Novice'), ('intermediate', 'Intermediate'), ('club', 'Club'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master'), ('elite', 'Elite')], db_index=True, default='intermediate', max_length=20),
        ),
        migrations.CreateModel(
            name='BotVictory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_elo', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victories', to='games.chessbot')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_victories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bot_elo'],
                'unique_together': {('user', 'bot')},
            },
        ),
    ]
