# Generated by Django 5.2.16 on 2026-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_gamechallenge_lobby_seek'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='unique_rematch_of_game',
        ),
        migrations.RemoveIndex(
            model_name='gamechallenge',
            name='games_gamec_status_opp_idx',
        ),
        migrations.AddField(
            model_name='game',
            name='is_tv_exhibition',
            field=models.BooleanField(db_index=True, default=False, help_text='Partie exhibition IA vs IA pour AFRICHESS TV (vraie partie Stockfish)'),
        ),
    ]
