/** Codes pays africains (alignés sur le backend User.Country). */
export const AFRICAN_COUNTRIES: { code: string; name: string }[] = [
  { code: "", name: "Tous les pays" },
  { code: "DZ", name: "Algérie" },
  { code: "AO", name: "Angola" },
  { code: "BJ", name: "Bénin" },
  { code: "BW", name: "Botswana" },
  { code: "BF", name: "Burkina Faso" },
  { code: "CM", name: "Cameroun" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "EG", name: "Égypte" },
  { code: "ET", name: "Éthiopie" },
  { code: "GH", name: "Ghana" },
  { code: "KE", name: "Kenya" },
  { code: "MA", name: "Maroc" },
  { code: "MG", name: "Madagascar" },
  { code: "ML", name: "Mali" },
  { code: "MR", name: "Mauritanie" },
  { code: "MU", name: "Maurice" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibie" },
  { code: "NG", name: "Nigeria" },
  { code: "RW", name: "Rwanda" },
  { code: "SN", name: "Sénégal" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "TN", name: "Tunisie" },
  { code: "TZ", name: "Tanzanie" },
  { code: "UG", name: "Ouganda" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" },
];
