export interface WorldCountry {
  code: string;
  nameEn: string;
  nameFr: string;
  isAfrican: boolean;
}

export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: "AF", nameEn: "Afghanistan", nameFr: "Afghanistan", isAfrican: false },
  { code: "ZA", nameEn: "South Africa", nameFr: "Afrique du Sud", isAfrican: true },
  { code: "AL", nameEn: "Albania", nameFr: "Albanie", isAfrican: false },
  { code: "DZ", nameEn: "Algeria", nameFr: "Algérie", isAfrican: true },
  { code: "DE", nameEn: "Germany", nameFr: "Allemagne", isAfrican: false },
  { code: "AD", nameEn: "Andorra", nameFr: "Andorre", isAfrican: false },
  { code: "AO", nameEn: "Angola", nameFr: "Angola", isAfrican: true },
  { code: "AI", nameEn: "Anguilla", nameFr: "Anguilla", isAfrican: false },
  { code: "AQ", nameEn: "Antarctica", nameFr: "Antarctique", isAfrican: false },
  { code: "AG", nameEn: "Antigua and Barbuda", nameFr: "Antigua-et-Barbuda", isAfrican: false },
  { code: "SA", nameEn: "Saudi Arabia", nameFr: "Arabie saoudite", isAfrican: false },
  { code: "AR", nameEn: "Argentina", nameFr: "Argentine", isAfrican: false },
  { code: "AM", nameEn: "Armenia", nameFr: "Arménie", isAfrican: false },
  { code: "AW", nameEn: "Aruba", nameFr: "Aruba", isAfrican: false },
  { code: "AU", nameEn: "Australia", nameFr: "Australie", isAfrican: false },
  { code: "XX", nameEn: "Other", nameFr: "Autre / non précisé", isAfrican: false },
  { code: "AT", nameEn: "Austria", nameFr: "Autriche", isAfrican: false },
  { code: "AZ", nameEn: "Azerbaijan", nameFr: "Azerbaïdjan", isAfrican: false },
  { code: "BS", nameEn: "Bahamas", nameFr: "Bahamas", isAfrican: false },
  { code: "BH", nameEn: "Bahrain", nameFr: "Bahreïn", isAfrican: false },
  { code: "BD", nameEn: "Bangladesh", nameFr: "Bangladesh", isAfrican: false },
  { code: "BB", nameEn: "Barbados", nameFr: "Barbade", isAfrican: false },
  { code: "BE", nameEn: "Belgium", nameFr: "Belgique", isAfrican: false },
  { code: "BZ", nameEn: "Belize", nameFr: "Belize", isAfrican: false },
  { code: "BM", nameEn: "Bermuda", nameFr: "Bermudes", isAfrican: false },
  { code: "BT", nameEn: "Bhutan", nameFr: "Bhoutan", isAfrican: false },
  { code: "BY", nameEn: "Belarus", nameFr: "Biélorussie", isAfrican: false },
  { code: "BO", nameEn: "Bolivia", nameFr: "Bolivie", isAfrican: false },
  { code: "BQ", nameEn: "Bonaire", nameFr: "Bonaire", isAfrican: false },
  { code: "BA", nameEn: "Bosnia and Herzegovina", nameFr: "Bosnie-Herzégovine", isAfrican: false },
  { code: "BW", nameEn: "Botswana", nameFr: "Botswana", isAfrican: true },
  { code: "BN", nameEn: "Brunei", nameFr: "Brunei", isAfrican: false },
  { code: "BR", nameEn: "Brazil", nameFr: "Brésil", isAfrican: false },
  { code: "BG", nameEn: "Bulgaria", nameFr: "Bulgarie", isAfrican: false },
  { code: "BF", nameEn: "Burkina Faso", nameFr: "Burkina Faso", isAfrican: true },
  { code: "BI", nameEn: "Burundi", nameFr: "Burundi", isAfrican: true },
  { code: "BJ", nameEn: "Benin", nameFr: "Bénin", isAfrican: true },
  { code: "KH", nameEn: "Cambodia", nameFr: "Cambodge", isAfrican: false },
  { code: "CM", nameEn: "Cameroon", nameFr: "Cameroun", isAfrican: true },
  { code: "CA", nameEn: "Canada", nameFr: "Canada", isAfrican: false },
  { code: "CV", nameEn: "Cabo Verde", nameFr: "Cap-Vert", isAfrican: true },
  { code: "CL", nameEn: "Chile", nameFr: "Chili", isAfrican: false },
  { code: "CN", nameEn: "China", nameFr: "Chine", isAfrican: false },
  { code: "CY", nameEn: "Cyprus", nameFr: "Chypre", isAfrican: false },
  { code: "CO", nameEn: "Colombia", nameFr: "Colombie", isAfrican: false },
  { code: "KM", nameEn: "Comoros", nameFr: "Comores", isAfrican: true },
  { code: "CG", nameEn: "Congo", nameFr: "Congo", isAfrican: true },
  { code: "KP", nameEn: "North Korea", nameFr: "Corée du Nord", isAfrican: false },
  { code: "KR", nameEn: "South Korea", nameFr: "Corée du Sud", isAfrican: false },
  { code: "CR", nameEn: "Costa Rica", nameFr: "Costa Rica", isAfrican: false },
  { code: "HR", nameEn: "Croatia", nameFr: "Croatie", isAfrican: false },
  { code: "CU", nameEn: "Cuba", nameFr: "Cuba", isAfrican: false },
  { code: "CW", nameEn: "Curaçao", nameFr: "Curaçao", isAfrican: false },
  { code: "CI", nameEn: "Côte d'Ivoire", nameFr: "Côte d\'Ivoire", isAfrican: true },
  { code: "DK", nameEn: "Denmark", nameFr: "Danemark", isAfrican: false },
  { code: "DJ", nameEn: "Djibouti", nameFr: "Djibouti", isAfrican: true },
  { code: "DM", nameEn: "Dominica", nameFr: "Dominique", isAfrican: false },
  { code: "ES", nameEn: "Spain", nameFr: "Espagne", isAfrican: false },
  { code: "EE", nameEn: "Estonia", nameFr: "Estonie", isAfrican: false },
  { code: "SZ", nameEn: "Eswatini", nameFr: "Eswatini", isAfrican: true },
  { code: "FJ", nameEn: "Fiji", nameFr: "Fidji", isAfrican: false },
  { code: "FI", nameEn: "Finland", nameFr: "Finlande", isAfrican: false },
  { code: "FR", nameEn: "France", nameFr: "France", isAfrican: false },
  { code: "GA", nameEn: "Gabon", nameFr: "Gabon", isAfrican: true },
  { code: "GM", nameEn: "Gambia", nameFr: "Gambie", isAfrican: true },
  { code: "GH", nameEn: "Ghana", nameFr: "Ghana", isAfrican: true },
  { code: "GI", nameEn: "Gibraltar", nameFr: "Gibraltar", isAfrican: false },
  { code: "GD", nameEn: "Grenada", nameFr: "Grenade", isAfrican: false },
  { code: "GL", nameEn: "Greenland", nameFr: "Groenland", isAfrican: false },
  { code: "GR", nameEn: "Greece", nameFr: "Grèce", isAfrican: false },
  { code: "GP", nameEn: "Guadeloupe", nameFr: "Guadeloupe", isAfrican: false },
  { code: "GU", nameEn: "Guam", nameFr: "Guam", isAfrican: false },
  { code: "GT", nameEn: "Guatemala", nameFr: "Guatemala", isAfrican: false },
  { code: "GG", nameEn: "Guernsey", nameFr: "Guernesey", isAfrican: false },
  { code: "GN", nameEn: "Guinea", nameFr: "Guinée", isAfrican: true },
  { code: "GQ", nameEn: "Equatorial Guinea", nameFr: "Guinée équatoriale", isAfrican: true },
  { code: "GW", nameEn: "Guinea-Bissau", nameFr: "Guinée-Bissau", isAfrican: true },
  { code: "GY", nameEn: "Guyana", nameFr: "Guyana", isAfrican: false },
  { code: "GF", nameEn: "French Guiana", nameFr: "Guyane française", isAfrican: false },
  { code: "GE", nameEn: "Georgia", nameFr: "Géorgie", isAfrican: false },
  { code: "GS", nameEn: "South Georgia", nameFr: "Géorgie du Sud", isAfrican: false },
  { code: "HT", nameEn: "Haiti", nameFr: "Haïti", isAfrican: false },
  { code: "HN", nameEn: "Honduras", nameFr: "Honduras", isAfrican: false },
  { code: "HK", nameEn: "Hong Kong", nameFr: "Hong Kong", isAfrican: false },
  { code: "HU", nameEn: "Hungary", nameFr: "Hongrie", isAfrican: false },
  { code: "IN", nameEn: "India", nameFr: "Inde", isAfrican: false },
  { code: "ID", nameEn: "Indonesia", nameFr: "Indonésie", isAfrican: false },
  { code: "IQ", nameEn: "Iraq", nameFr: "Irak", isAfrican: false },
  { code: "IR", nameEn: "Iran", nameFr: "Iran", isAfrican: false },
  { code: "IE", nameEn: "Ireland", nameFr: "Irlande", isAfrican: false },
  { code: "IS", nameEn: "Iceland", nameFr: "Islande", isAfrican: false },
  { code: "IL", nameEn: "Israel", nameFr: "Israël", isAfrican: false },
  { code: "IT", nameEn: "Italy", nameFr: "Italie", isAfrican: false },
  { code: "JM", nameEn: "Jamaica", nameFr: "Jamaïque", isAfrican: false },
  { code: "JP", nameEn: "Japan", nameFr: "Japon", isAfrican: false },
  { code: "JE", nameEn: "Jersey", nameFr: "Jersey", isAfrican: false },
  { code: "JO", nameEn: "Jordan", nameFr: "Jordanie", isAfrican: false },
  { code: "KZ", nameEn: "Kazakhstan", nameFr: "Kazakhstan", isAfrican: false },
  { code: "KE", nameEn: "Kenya", nameFr: "Kenya", isAfrican: true },
  { code: "KG", nameEn: "Kyrgyzstan", nameFr: "Kirghizistan", isAfrican: false },
  { code: "KI", nameEn: "Kiribati", nameFr: "Kiribati", isAfrican: false },
  { code: "KW", nameEn: "Kuwait", nameFr: "Koweït", isAfrican: false },
  { code: "RE", nameEn: "Réunion", nameFr: "La Réunion", isAfrican: true },
  { code: "LA", nameEn: "Laos", nameFr: "Laos", isAfrican: false },
  { code: "LS", nameEn: "Lesotho", nameFr: "Lesotho", isAfrican: true },
  { code: "LV", nameEn: "Latvia", nameFr: "Lettonie", isAfrican: false },
  { code: "LB", nameEn: "Lebanon", nameFr: "Liban", isAfrican: false },
  { code: "LY", nameEn: "Libya", nameFr: "Libye", isAfrican: true },
  { code: "LR", nameEn: "Liberia", nameFr: "Libéria", isAfrican: true },
  { code: "LI", nameEn: "Liechtenstein", nameFr: "Liechtenstein", isAfrican: false },
  { code: "LT", nameEn: "Lithuania", nameFr: "Lituanie", isAfrican: false },
  { code: "LU", nameEn: "Luxembourg", nameFr: "Luxembourg", isAfrican: false },
  { code: "MO", nameEn: "Macao", nameFr: "Macao", isAfrican: false },
  { code: "MK", nameEn: "North Macedonia", nameFr: "Macédoine du Nord", isAfrican: false },
  { code: "MG", nameEn: "Madagascar", nameFr: "Madagascar", isAfrican: true },
  { code: "MY", nameEn: "Malaysia", nameFr: "Malaisie", isAfrican: false },
  { code: "MW", nameEn: "Malawi", nameFr: "Malawi", isAfrican: true },
  { code: "MV", nameEn: "Maldives", nameFr: "Maldives", isAfrican: false },
  { code: "ML", nameEn: "Mali", nameFr: "Mali", isAfrican: true },
  { code: "MT", nameEn: "Malta", nameFr: "Malte", isAfrican: false },
  { code: "MA", nameEn: "Morocco", nameFr: "Maroc", isAfrican: true },
  { code: "MQ", nameEn: "Martinique", nameFr: "Martinique", isAfrican: false },
  { code: "MU", nameEn: "Mauritius", nameFr: "Maurice", isAfrican: true },
  { code: "MR", nameEn: "Mauritania", nameFr: "Mauritanie", isAfrican: true },
  { code: "YT", nameEn: "Mayotte", nameFr: "Mayotte", isAfrican: true },
  { code: "MX", nameEn: "Mexico", nameFr: "Mexique", isAfrican: false },
  { code: "FM", nameEn: "Micronesia", nameFr: "Micronésie", isAfrican: false },
  { code: "MD", nameEn: "Moldova", nameFr: "Moldavie", isAfrican: false },
  { code: "MC", nameEn: "Monaco", nameFr: "Monaco", isAfrican: false },
  { code: "MN", nameEn: "Mongolia", nameFr: "Mongolie", isAfrican: false },
  { code: "MS", nameEn: "Montserrat", nameFr: "Montserrat", isAfrican: false },
  { code: "ME", nameEn: "Montenegro", nameFr: "Monténégro", isAfrican: false },
  { code: "MZ", nameEn: "Mozambique", nameFr: "Mozambique", isAfrican: true },
  { code: "MM", nameEn: "Myanmar", nameFr: "Myanmar", isAfrican: false },
  { code: "NA", nameEn: "Namibia", nameFr: "Namibie", isAfrican: true },
  { code: "NR", nameEn: "Nauru", nameFr: "Nauru", isAfrican: false },
  { code: "NI", nameEn: "Nicaragua", nameFr: "Nicaragua", isAfrican: false },
  { code: "NE", nameEn: "Niger", nameFr: "Niger", isAfrican: true },
  { code: "NG", nameEn: "Nigeria", nameFr: "Nigeria", isAfrican: true },
  { code: "NU", nameEn: "Niue", nameFr: "Niue", isAfrican: false },
  { code: "NO", nameEn: "Norway", nameFr: "Norvège", isAfrican: false },
  { code: "NC", nameEn: "New Caledonia", nameFr: "Nouvelle-Calédonie", isAfrican: false },
  { code: "NZ", nameEn: "New Zealand", nameFr: "Nouvelle-Zélande", isAfrican: false },
  { code: "NP", nameEn: "Nepal", nameFr: "Népal", isAfrican: false },
  { code: "OM", nameEn: "Oman", nameFr: "Oman", isAfrican: false },
  { code: "UG", nameEn: "Uganda", nameFr: "Ouganda", isAfrican: true },
  { code: "UZ", nameEn: "Uzbekistan", nameFr: "Ouzbékistan", isAfrican: false },
  { code: "PK", nameEn: "Pakistan", nameFr: "Pakistan", isAfrican: false },
  { code: "PW", nameEn: "Palau", nameFr: "Palaos", isAfrican: false },
  { code: "PS", nameEn: "Palestine", nameFr: "Palestine", isAfrican: false },
  { code: "PA", nameEn: "Panama", nameFr: "Panama", isAfrican: false },
  { code: "PG", nameEn: "Papua New Guinea", nameFr: "Papouasie-Nouvelle-Guinée", isAfrican: false },
  { code: "PY", nameEn: "Paraguay", nameFr: "Paraguay", isAfrican: false },
  { code: "NL", nameEn: "Netherlands", nameFr: "Pays-Bas", isAfrican: false },
  { code: "PH", nameEn: "Philippines", nameFr: "Philippines", isAfrican: false },
  { code: "PN", nameEn: "Pitcairn", nameFr: "Pitcairn", isAfrican: false },
  { code: "PL", nameEn: "Poland", nameFr: "Pologne", isAfrican: false },
  { code: "PF", nameEn: "French Polynesia", nameFr: "Polynésie française", isAfrican: false },
  { code: "PR", nameEn: "Puerto Rico", nameFr: "Porto Rico", isAfrican: false },
  { code: "PT", nameEn: "Portugal", nameFr: "Portugal", isAfrican: false },
  { code: "PE", nameEn: "Peru", nameFr: "Pérou", isAfrican: false },
  { code: "QA", nameEn: "Qatar", nameFr: "Qatar", isAfrican: false },
  { code: "CD", nameEn: "DR Congo", nameFr: "RD Congo", isAfrican: true },
  { code: "RO", nameEn: "Romania", nameFr: "Roumanie", isAfrican: false },
  { code: "GB", nameEn: "United Kingdom", nameFr: "Royaume-Uni", isAfrican: false },
  { code: "RU", nameEn: "Russia", nameFr: "Russie", isAfrican: false },
  { code: "RW", nameEn: "Rwanda", nameFr: "Rwanda", isAfrican: true },
  { code: "CF", nameEn: "Central African Republic", nameFr: "République centrafricaine", isAfrican: true },
  { code: "DO", nameEn: "Dominican Republic", nameFr: "République dominicaine", isAfrican: false },
  { code: "EH", nameEn: "Western Sahara", nameFr: "Sahara occidental", isAfrican: true },
  { code: "BL", nameEn: "Saint Barthélemy", nameFr: "Saint-Barthélemy", isAfrican: false },
  { code: "KN", nameEn: "Saint Kitts and Nevis", nameFr: "Saint-Kitts-et-Nevis", isAfrican: false },
  { code: "SM", nameEn: "San Marino", nameFr: "Saint-Marin", isAfrican: false },
  { code: "MF", nameEn: "Saint Martin", nameFr: "Saint-Martin", isAfrican: false },
  { code: "SX", nameEn: "Sint Maarten", nameFr: "Saint-Martin (Pays-Bas)", isAfrican: false },
  { code: "PM", nameEn: "Saint Pierre and Miquelon", nameFr: "Saint-Pierre-et-Miquelon", isAfrican: false },
  { code: "VC", nameEn: "Saint Vincent", nameFr: "Saint-Vincent-et-les-Grenadines", isAfrican: false },
  { code: "SH", nameEn: "Saint Helena", nameFr: "Sainte-Hélène", isAfrican: true },
  { code: "LC", nameEn: "Saint Lucia", nameFr: "Sainte-Lucie", isAfrican: false },
  { code: "SV", nameEn: "El Salvador", nameFr: "Salvador", isAfrican: false },
  { code: "WS", nameEn: "Samoa", nameFr: "Samoa", isAfrican: false },
  { code: "AS", nameEn: "American Samoa", nameFr: "Samoa américaines", isAfrican: false },
  { code: "RS", nameEn: "Serbia", nameFr: "Serbie", isAfrican: false },
  { code: "SC", nameEn: "Seychelles", nameFr: "Seychelles", isAfrican: true },
  { code: "SL", nameEn: "Sierra Leone", nameFr: "Sierra Leone", isAfrican: true },
  { code: "SG", nameEn: "Singapore", nameFr: "Singapour", isAfrican: false },
  { code: "SK", nameEn: "Slovakia", nameFr: "Slovaquie", isAfrican: false },
  { code: "SI", nameEn: "Slovenia", nameFr: "Slovénie", isAfrican: false },
  { code: "SO", nameEn: "Somalia", nameFr: "Somalie", isAfrican: true },
  { code: "SD", nameEn: "Sudan", nameFr: "Soudan", isAfrican: true },
  { code: "SS", nameEn: "South Sudan", nameFr: "Soudan du Sud", isAfrican: true },
  { code: "LK", nameEn: "Sri Lanka", nameFr: "Sri Lanka", isAfrican: false },
  { code: "CH", nameEn: "Switzerland", nameFr: "Suisse", isAfrican: false },
  { code: "SR", nameEn: "Suriname", nameFr: "Suriname", isAfrican: false },
  { code: "SE", nameEn: "Sweden", nameFr: "Suède", isAfrican: false },
  { code: "SJ", nameEn: "Svalbard", nameFr: "Svalbard", isAfrican: false },
  { code: "SY", nameEn: "Syria", nameFr: "Syrie", isAfrican: false },
  { code: "ST", nameEn: "São Tomé and Príncipe", nameFr: "São Tomé-et-Príncipe", isAfrican: true },
  { code: "SN", nameEn: "Senegal", nameFr: "Sénégal", isAfrican: true },
  { code: "TJ", nameEn: "Tajikistan", nameFr: "Tadjikistan", isAfrican: false },
  { code: "TZ", nameEn: "Tanzania", nameFr: "Tanzanie", isAfrican: true },
  { code: "TW", nameEn: "Taiwan", nameFr: "Taïwan", isAfrican: false },
  { code: "TD", nameEn: "Chad", nameFr: "Tchad", isAfrican: true },
  { code: "CZ", nameEn: "Czechia", nameFr: "Tchéquie", isAfrican: false },
  { code: "TF", nameEn: "French Southern Territories", nameFr: "Terres australes françaises", isAfrican: false },
  { code: "IO", nameEn: "British Indian Ocean Territory", nameFr: "Territoire britannique de l\'océan Indien", isAfrican: false },
  { code: "TH", nameEn: "Thailand", nameFr: "Thaïlande", isAfrican: false },
  { code: "TL", nameEn: "Timor-Leste", nameFr: "Timor oriental", isAfrican: false },
  { code: "TG", nameEn: "Togo", nameFr: "Togo", isAfrican: true },
  { code: "TK", nameEn: "Tokelau", nameFr: "Tokelau", isAfrican: false },
  { code: "TO", nameEn: "Tonga", nameFr: "Tonga", isAfrican: false },
  { code: "TT", nameEn: "Trinidad and Tobago", nameFr: "Trinité-et-Tobago", isAfrican: false },
  { code: "TN", nameEn: "Tunisia", nameFr: "Tunisie", isAfrican: true },
  { code: "TM", nameEn: "Turkmenistan", nameFr: "Turkménistan", isAfrican: false },
  { code: "TR", nameEn: "Turkey", nameFr: "Turquie", isAfrican: false },
  { code: "TV", nameEn: "Tuvalu", nameFr: "Tuvalu", isAfrican: false },
  { code: "UA", nameEn: "Ukraine", nameFr: "Ukraine", isAfrican: false },
  { code: "UY", nameEn: "Uruguay", nameFr: "Uruguay", isAfrican: false },
  { code: "VU", nameEn: "Vanuatu", nameFr: "Vanuatu", isAfrican: false },
  { code: "VA", nameEn: "Holy See", nameFr: "Vatican", isAfrican: false },
  { code: "VE", nameEn: "Venezuela", nameFr: "Venezuela", isAfrican: false },
  { code: "VN", nameEn: "Vietnam", nameFr: "Viêt Nam", isAfrican: false },
  { code: "WF", nameEn: "Wallis and Futuna", nameFr: "Wallis-et-Futuna", isAfrican: false },
  { code: "YE", nameEn: "Yemen", nameFr: "Yémen", isAfrican: false },
  { code: "ZM", nameEn: "Zambia", nameFr: "Zambie", isAfrican: true },
  { code: "ZW", nameEn: "Zimbabwe", nameFr: "Zimbabwe", isAfrican: true },
  { code: "AX", nameEn: "Åland Islands", nameFr: "Åland", isAfrican: false },
  { code: "EG", nameEn: "Egypt", nameFr: "Égypte", isAfrican: true },
  { code: "AE", nameEn: "United Arab Emirates", nameFr: "Émirats arabes unis", isAfrican: false },
  { code: "EC", nameEn: "Ecuador", nameFr: "Équateur", isAfrican: false },
  { code: "ER", nameEn: "Eritrea", nameFr: "Érythrée", isAfrican: true },
  { code: "US", nameEn: "United States", nameFr: "États-Unis", isAfrican: false },
  { code: "ET", nameEn: "Ethiopia", nameFr: "Éthiopie", isAfrican: true },
  { code: "BV", nameEn: "Bouvet Island", nameFr: "Île Bouvet", isAfrican: false },
  { code: "CX", nameEn: "Christmas Island", nameFr: "Île Christmas", isAfrican: false },
  { code: "NF", nameEn: "Norfolk Island", nameFr: "Île Norfolk", isAfrican: false },
  { code: "IM", nameEn: "Isle of Man", nameFr: "Île de Man", isAfrican: false },
  { code: "KY", nameEn: "Cayman Islands", nameFr: "Îles Caïmans", isAfrican: false },
  { code: "CC", nameEn: "Cocos Islands", nameFr: "Îles Cocos", isAfrican: false },
  { code: "CK", nameEn: "Cook Islands", nameFr: "Îles Cook", isAfrican: false },
  { code: "FO", nameEn: "Faroe Islands", nameFr: "Îles Féroé", isAfrican: false },
  { code: "HM", nameEn: "Heard Island", nameFr: "Îles Heard-et-MacDonald", isAfrican: false },
  { code: "FK", nameEn: "Falkland Islands", nameFr: "Îles Malouines", isAfrican: false },
  { code: "MP", nameEn: "Northern Mariana Islands", nameFr: "Îles Mariannes du Nord", isAfrican: false },
  { code: "MH", nameEn: "Marshall Islands", nameFr: "Îles Marshall", isAfrican: false },
  { code: "SB", nameEn: "Solomon Islands", nameFr: "Îles Salomon", isAfrican: false },
  { code: "TC", nameEn: "Turks and Caicos", nameFr: "Îles Turques-et-Caïques", isAfrican: false },
  { code: "VI", nameEn: "Virgin Islands (US)", nameFr: "Îles Vierges américaines", isAfrican: false },
  { code: "VG", nameEn: "Virgin Islands (UK)", nameFr: "Îles Vierges britanniques", isAfrican: false },
  { code: "UM", nameEn: "US Minor Outlying Islands", nameFr: "Îles mineures éloignées des États-Unis", isAfrican: false },
];

export const AFRICAN_COUNTRY_CODES = new Set([
  "AO",
  "BF",
  "BI",
  "BJ",
  "BW",
  "CD",
  "CF",
  "CG",
  "CI",
  "CM",
  "CV",
  "DJ",
  "DZ",
  "EG",
  "EH",
  "ER",
  "ET",
  "GA",
  "GH",
  "GM",
  "GN",
  "GQ",
  "GW",
  "KE",
  "KM",
  "LR",
  "LS",
  "LY",
  "MA",
  "MG",
  "ML",
  "MR",
  "MU",
  "MW",
  "MZ",
  "NA",
  "NE",
  "NG",
  "RE",
  "RW",
  "SC",
  "SD",
  "SH",
  "SL",
  "SN",
  "SO",
  "SS",
  "ST",
  "SZ",
  "TD",
  "TG",
  "TN",
  "TZ",
  "UG",
  "YT",
  "ZA",
  "ZM",
  "ZW",
]);

export function countryFlag(code: string): string {
  if (!code || code === "XX" || code.length !== 2) return "🌍";
  const u = code.toUpperCase();
  return String.fromCodePoint(...Array.from(u).map((c) => 0x1f1e6 - 65 + c.charCodeAt(0)));
}

export function countryName(country: WorldCountry, locale: string): string {
  return locale === "fr" ? country.nameFr : country.nameEn;
}

export function sortedCountries(locale: string): WorldCountry[] {
  const african = WORLD_COUNTRIES.filter((c) => c.isAfrican).sort((a, b) => countryName(a, locale).localeCompare(countryName(b, locale), locale));
  const other = WORLD_COUNTRIES.filter((c) => !c.isAfrican).sort((a, b) => countryName(a, locale).localeCompare(countryName(b, locale), locale));
  return [...african, ...other];
}
